### ISSUE TITLE
Item name is saved globally

### ISSUE THREAD

**Issue by fwolter** [MitchMcKean/mccontrol#4]
When I change the target Item name of a button, the target Items of all buttons are changed. As a result, you can only use one button to control openHAB.

**Comment by MitchMcKean** [comment]
yea as I was writing the code I was thinking of only using it whit openHab. With that in mind, typically you would only have one openHab server. So you put the main apiLink in the field RestAPI-link for example https://192.168.151.123/rest/items/ and the name of the item from openHab in the field called ItemName. McControl will then add the itemName to the link. So it your item is called switch01 then McControl will use the link https://192.168.151.123/rest/items/switch01 

I made it so because if you might change the ip of your openHab, you would only need to update the config of one button and it would be applied to every other. 

but yea, I think I should change that. thank you for your feedback.

**Comment by fwolter** [comment]
Not sure if I understand your answer correctly. I spoke solely about the `itemName` parameter.

Turned out the firmware of the Stream Deck Mini was the cause. I updated it from 3.00.000 to 3.00.001 and the `itemName` can be configured individually for every button.
